
package fr.eseo.jee.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Fri Mar 23 13:58:49 CET 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "reserverTaxiResponse", namespace = "http://ws.jee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reserverTaxiResponse", namespace = "http://ws.jee.eseo.fr/")

public class ReserverTaxiResponse {


}

