
package fr.eseo.jee.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Fri Mar 23 13:58:49 CET 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "trouverTaxiResponse", namespace = "http://ws.jee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverTaxiResponse", namespace = "http://ws.jee.eseo.fr/")

public class TrouverTaxiResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<fr.eseo.jee.beans.Taxi> _return;

    public java.util.ArrayList<fr.eseo.jee.beans.Taxi> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<fr.eseo.jee.beans.Taxi> new_return)  {
        this._return = new_return;
    }

}

